Repository codeit-sprint-team1/Taskify, pull requests merged in 2023-12, with the labels that each got.

#26 docs: Issue template 설정
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/refactor.md
Labels: 문서📃

#31 feat: 공용 Input 컴포넌트 추가
  components/common/Input.tsx
  components/index.ts
Labels: 기능구현 🚀

#32 feat: 공용 버튼 컴포넌트 생성
  components/common/Button.tsx
  components/index.ts
Labels: 기능구현 🚀

#34 feat: pxr 단위 설정 함수 tailwind config에 추가
  tailwind.config.ts
Labels: 기능구현 🚀

#35 refactor: 버튼 반응형 사이즈 추가 및 기본 타입 button으로 수정
  components/common/Button.tsx
Labels: 리팩토링 🔨

#38 refactor: tailwind pxr 단위 범위 시작 0으로 수정
  tailwind.config.ts
Labels: 리팩토링 🔨

#39 Featuer: 로그인/회원가입 페이지 기본기능 구현
  components/common/.gitkeep
  components/common/Button.tsx
  components/common/Input.tsx
  components/common/PasswordInput.tsx
  components/index.ts
  components/sign/constants.ts
  components/sign/data/index.ts
  components/sign/data/useCheckEmailDuplicate.ts
  components/sign/data/useLogin.tsx
  components/sign/data/useSignup.tsx
  components/sign/data/useTokenRedirect.tsx
  components/sign/footer/SignFooter.tsx
  components/sign/form/LoginForm.tsx
  components/sign/form/SignUpForm.tsx
  components/sign/header/SignHeader.tsx
  components/sign/index.ts
  constants/.gitkeep
  constants/constants.js
  page-layout/SignLayout.tsx
  pages/login/index.tsx
  pages/signup/index.tsx
  public/icons/logo.svg
  public/icons/mainIcon.svg
  public/icons/visibility_off.svg
  public/icons/visibility_on.svg
  utils/axiosInstance.js
  utils/index.js
  utils/useAsync.ts
Labels: 기능구현 🚀

#43 refactor: login, signup form 라벨표현, 버튼활성화, 컴포넌트 import 방식 변경
  components/common/Button.tsx
  components/common/Input.tsx
  components/common/PasswordInput.tsx
  components/index.ts
  components/sign/footer/SignFooter.tsx
  components/sign/form/LoginForm.tsx
  components/sign/form/SignUpForm.tsx
  components/sign/header/SignHeader.tsx
  pages/login/index.tsx
  pages/signup/index.tsx
Labels: 리팩토링 🔨

#44 refactor: 컴포넌트 index.ts 파일 수정
  components/index.ts
Labels: 리팩토링 🔨

#46 refactor: axios auth 인스턴스 추가
  components/sign/data/useCheckEmailDuplicate.ts
  components/sign/data/useLogin.tsx
  components/sign/data/useSignup.tsx
  hooks/.gitkeep
  hooks/useAsync.ts
  utils/.gitkeep
  utils/axiosInstance.js
  utils/axiosInstance.ts
  utils/index.ts
Labels: 리팩토링 🔨

#47 refactor: 컬러칩 색상코드값, colorName 키 추가
  components/common/ColorChips.tsx
Labels: 리팩토링 🔨

#45 feat: zustand로 userInfo store 생성
  components/sign/form/LoginForm.tsx
  components/sign/form/SignUpForm.tsx
  store/memos/index.ts
  store/memos/useUserInfo.ts
Labels: 기능구현 🚀

#37 feat: 랜딩 페이지 제작
  pages/index.tsx
  public/icons/.gitkeep
  public/icons/landing/email-icon.svg
  public/icons/landing/facebook-icon.svg
  public/icons/landing/instagram-icon.svg
  public/images/.gitkeep
  public/images/landing/card1-img.png
  public/images/landing/card2-img.png
  public/images/landing/card3-img.png
  public/images/landing/header-logo.svg
  public/images/landing/point1-img.png
  public/images/landing/point2-img.png
  public/images/landing/taskify-top-img.png
  styles/globals.css
  tailwind.config.ts
Labels: 기능구현 🚀

#52 feat: 프로필 이미지 컴포넌트 추가
  components/dashboard/header/ProfileImage.tsx
  package-lock.json
Labels: 기능구현 🚀

#55 feat: 프로필 컴포넌트 추가
  components/common/Profile.tsx
  components/common/ProfileImage.tsx
  components/index.ts
Labels: 기능구현 🚀, 리팩토링 🔨

#57 feat: api types 선언
  types/auth.ts
  types/cards.ts
  types/columns.ts
  types/comments.ts
  types/dashboards.ts
  types/invitations.ts
  types/members.ts
  types/users.ts
Labels: 기능구현 🚀

#58 fix: userInfoType 수정
  store/memos/useUserInfo.ts
Labels: 버그 🐞

#59 refactor: button desktop tablet mobile size 반응형 삭제
  components/common/Button.tsx
Labels: 리팩토링 🔨

#65 feat: Textarea/Selectdate/ImagePick/Label 컴포넌트 제작
  components/common/ColorChips.tsx
  components/common/Input.tsx
  components/common/Label.tsx
  components/common/PasswordInput.tsx
  components/common/Textarea.tsx
  components/index.ts
  components/modal/ImagePick.tsx
  components/modal/SelectDate.tsx
  components/modal/constants.ts
  components/modal/data/usePostDashboard.ts.ts
  components/modal/type.ts
  components/sign/header/SignHeader.tsx
  page-layout/SignLayout.tsx
  pages/test/index.tsx
  public/icons/add-icon.svg
  public/icons/calendar-icon.svg
  public/icons/check-Icon.svg
  public/icons/logo-icon.svg
  public/icons/main-icon.svg
  public/icons/visibility_off-icon.svg
  public/icons/visibility_on-icon.svg
  tailwind.config.ts
Labels: 기능구현 🚀

#67 feat: 대시보드 헤더 추가
  components/dashboard/data/useGetDashboardList.tsx
  components/dashboard/header/DashboardHeader.tsx
  components/dashboard/header/Header.tsx
  components/dashboard/header/HeaderButton.tsx
  components/index.ts
  components/sign/header/SignHeader.tsx
  page-layout/DashboardLayout.tsx
  public/icons/add-icon.svg
  public/icons/add_box-icon.svg
  public/icons/check-icon.svg
  public/icons/crown-icon.svg
  public/icons/logo_large-icon.svg
  public/icons/logo_small-icon.svg
  public/icons/setting-icon.svg
  types/dashboards.ts
Labels: 기능구현 🚀

#68 feat: 보드 수정 페이지 추가
  components/boardEdit/ArrowBackButton.tsx
  components/boardEdit/InviteListTable.tsx
  components/boardEdit/MembersTable.tsx
  components/boardEdit/NameEditForm.tsx
  components/boardEdit/data/useDeleteDashboard.ts
  components/boardEdit/data/useDeleteMember.ts
  components/boardEdit/data/useGetDashboard.ts
  components/boardEdit/data/useGetInvitaions.ts
  components/boardEdit/data/useGetMembers.ts
  components/boardEdit/data/usePutDashboard.ts
  components/common/Button.tsx
  components/common/PaginationButton.tsx
  components/index.ts
  hooks/useAsync.ts
  next.config.js
  page-layout/BoardEditLayout.tsx
  pages/board/[boardid]/edit/index.tsx
  public/icons/arrowBackIcon.svg
  public/icons/arrowLeftIcon.svg
  public/icons/arrowRightIcon.svg
  public/icons/inviteIcon.svg
  tailwind.config.ts
  types/dashboards.ts
Labels: 기능구현 🚀

#70 feat: 마이페이지 레이아웃 추가
  components/index.ts
  components/mypage/MypageProfile.tsx
  components/mypage/PasswordModify.tsx
  page-layout/MyPageLayout.tsx
  pages/mypage/index.tsx
  public/icons/check-Icon.svg
Labels: 기능구현 🚀

#74 refactor: 체크아이콘 추가
  components/common/ColorChips.tsx
  public/icons/checkIcon.svg
Labels: 리팩토링 🔨

#71 feat: mydashboard 페이지 레이아웃 및 기본 기능 구현
  components/index.ts
  components/myBoard/DashBoards.tsx
  components/myBoard/InvitationsDashBoards.tsx
  pages/myboard/index.tsx
  public/icons/arrow-icon.svg
  public/icons/invitations-not-valid-icon.svg
  public/icons/plus-icon.svg
  public/icons/search-icon.svg
Labels: 기능구현 🚀

#72 feat: dashboard 사이드바 추가
  components/dashboard/data/useGetDashboards.tsx
  components/dashboard/sidebar/CreateDashboardButton.tsx
  components/dashboard/sidebar/DashboardSidebar.tsx
  components/index.ts
  components/modal/CreateDashboardModal.tsx
  components/modal/data/usePostDashboard.ts
  components/modal/data/usePostDashboards.ts
  pages/dashboard/[id].tsx
  pages/mydashboard/index.tsx
  store/memos/useDashboardList.ts
Labels: 기능구현 🚀, 리팩토링 🔨

#76 feat: 컬럼상태/ 상태드롭다운 컴포넌트 제작
  components/common/ColumnState.tsx
  components/common/ProfileImage.tsx
  components/modal/DropdownManager.tsx
  components/modal/DropdownState.tsx
  pages/test/index.tsx
Labels: 기능구현 🚀

#77 refactor: 공용 Input 컴포넌트 rest props와 className 프롭 추가
  components/common/Input.tsx
Labels: 리팩토링 🔨

#80 feat: 프로필 수정 기능 추가
  components/common/ProfileImage.tsx
  components/common/Toast.tsx
  components/index.ts
  components/mypage/MypageProfile.tsx
  components/mypage/data/usePostProfileImage.ts
  hooks/useAsync.ts
  next.config.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/mypage/index.tsx
Labels: 기능구현 🚀

#82 style: passwordInput 눈아이콘 위치 조정
  components/common/PasswordInput.tsx
  components/dashboard/sidebar/CreateDashboardButton.tsx
  components/index.ts
  components/modal/create-dashboard/CreateDashboardModal.tsx
  components/sign/form/LoginForm.tsx
  components/sign/form/SignUpForm.tsx
Labels: 리팩토링 🔨

#83 refactor: 라벨/인풋/로그인/회원가입 페이지 수정
  components/common/Input.tsx
  components/common/Label.tsx
  components/common/PasswordInput.tsx
  components/modal/ImagePick.tsx
  components/sign/form/LoginForm.tsx
  components/sign/form/SignUpForm.tsx
Labels: 도움!!! 😹, 리팩토링 🔨

#89 feat: 비밀번호 수정 기능 추가
  components/mypage/MypageProfile.tsx
  components/mypage/PasswordModify.tsx
  components/sign/constants.ts
Labels: 기능구현 🚀

#86 feat: 초대하기 모달, 헤더 구성원 컴포넌트 추가
  components/boardEdit/NameEditForm.tsx
  components/common/ProfileImage.tsx
  components/dashboard/header/DashboardHeader.tsx
  components/dashboard/header/Header.tsx
  components/dashboard/header/HeaderButton.tsx
  components/dashboard/header/HeaderMembers.tsx
  components/dashboard/header/InviteButton.tsx
  components/index.ts
  components/login/.gitkeep
  components/modal/Invite/InviteModal.tsx
  components/modal/Modal.tsx
  components/modal/ModalButton.tsx
  components/modal/create-dashboard/CreateDashboardModal.tsx
  components/modal/data/usePostInvitations.ts
  pages/dashboard/[id].tsx
  pages/dashboard/[id]/edit/index.tsx
  store/memos/useDashboardList.ts
  types/invitations.ts
Labels: 기능구현 🚀

#88 feat: 컬럼생성 usePostColumn 훅 및 새 컬럼 생성 모달 추가
  components/index.ts
  components/modal/create-column/createColumnModal.tsx
  components/modal/data/usePostColumns.ts
Labels: 기능구현 🚀

#90 fix: header 컴포넌트 prop 타입 오류 수정
  components/dashboard/header/Header.tsx
  components/index.ts
Labels: 버그 🐞

#92 Fix/error
  components/dashboard/header/Header.tsx
  components/dashboard/sidebar/DashboardSidebar.tsx
  components/modal/create-dashboard/CreateDashboardModal.tsx
  pages/mydashboard/index.tsx
Labels: 버그 🐞

#91 feat: 태그 / 태그추가 컴포넌트 제작
  .gitignore
  components/common/Input.tsx
  components/common/Tag.tsx
  components/index.ts
  components/modal/DropdownManager.tsx
  components/modal/DropdownState.tsx
  components/modal/edit-card/AddTag.tsx
  components/modal/edit-card/calculateLength.ts
  public/icons/cancel-icon.svg
Labels: 기능구현 🚀

#98 feat: 컬럼 삭제 확인 모달 추가
  components/dashboard/data/useDeleteColumns.tsx
  components/dashboard/data/useGetDashboards.tsx
  components/modal/Modal.tsx
  components/modal/delete-column/DeleteColumnConfirmModal.tsx
  hooks/useAsync.ts
Labels: 기능구현 🚀

#101 feat: 대시보드 페이지 레이아웃 구현
  components/dashboard/column.tsx
  page-layout/DashboardLayout.tsx
  pages/dashboard/[id].tsx
  public/icons/boards/calendar.svg
  public/icons/boards/card-desktop-settings.svg
  public/icons/boards/card-dot.svg
  public/icons/boards/plus.svg
  public/icons/boards/test-img.png
  tailwind.config.ts
Labels: 기능구현 🚀

#102 feat: 나의 대시보드 페이지 구현 및 API 연결
  components/myBoard/DashBoards.tsx
  components/myBoard/InvitationsDashBoards.tsx
  components/myBoard/MyDashBoards.tsx
  components/myBoard/data/useGetDashBoards.ts
  components/myBoard/data/useGetInvitations.ts
  components/myBoard/data/usePutInvitations.ts
  pages/index.tsx
  pages/mydashboard/index.tsx
Labels: 기능구현 🚀
