Repository codeit-sprint-team1/Taskify, pull requests merged in 2024-01, with the labels that each got.

#105 feat: 컬럼 수정 모달 추가
  components/dashboard/data/usePutColumns.ts
  components/index.ts
  components/modal/create-column/createColumnModal.tsx
  components/modal/create-dashboard/CreateDashboardModal.tsx
  components/modal/data/usePostColumns.ts
  components/modal/data/usePostDashboards.ts
  components/modal/edit-column/DeleteColumnConfirmModal.tsx
  components/modal/edit-column/EditColumnModal.tsx
  components/myBoard/DashBoards.tsx
Labels: 기능구현 🚀

#112 fix: 로그아웃 후 라우팅 오류 수정
  components/dashboard/header/ProfileDropdownMenu.tsx
Labels: 버그 🐞

#120 feat: 사이드바 타이틀 고정 및 모바일에서 클릭시 오픈되도록 구현
  components/boardEdit/NameEditForm.tsx
  components/dashboard/header/ProfileDropdownMenu.tsx
  components/dashboard/sidebar/DashboardSidebar.tsx
  components/modal/create-dashboard/CreateDashboardModal.tsx
  components/myBoard/DashBoards.tsx
  pages/dashboard/[id].tsx
  pages/dashboard/[id]/edit/index.tsx
  pages/mydashboard/index.tsx
  store/memos/index.ts
  store/memos/useDashboardList.ts
Labels: 기능구현 🚀, 리팩토링 🔨

#123 refactor: 헤더 정렬 수정
  components/dashboard/header/Header.tsx
Labels: 버그 🐞, 리팩토링 🔨

#122 feat: 파비콘 추가 타이틀 수정 footer FAQ, 아이콘 수정
  pages/_app.tsx
  pages/index.tsx
  public/icons/favicon.ico
  public/icons/github.svg
  public/icons/kakaotalk.svg
Labels: 리팩토링 🔨

#124 feat: 할일생성 카드 모달
  components/common/Input.tsx
  components/common/Label.tsx
  components/common/Textarea.tsx
  components/dashboard/column.tsx
  components/modal/DropdownManager.tsx
  components/modal/ImagePick.tsx
  components/modal/Modal.tsx
  components/modal/SelectDate.tsx
  components/modal/create-card/CreateCardModal.tsx
  components/modal/create-card/data/usePostCard.tsx
  components/modal/edit-card/AddTag.tsx
  components/sign/form/LoginForm.tsx
  pages/test/index.tsx
  styles/globals.css
  types/cards.ts
  types/columns.ts
Labels: 기능구현 🚀

#125 refactor: 상태 드롭다운 API 연결
  components/modal/DropdownState.tsx
  hooks/useOnClickOutside.ts
Labels: 리팩토링 🔨

#126 refacotr: 회원가입 성공 메시지 notify로 수정
  components/sign/form/SignUpForm.tsx
Labels: 리팩토링 🔨

#128 style: 회원가입/로그인 페이지 로고 위치조정
  components/sign/header/SignHeader.tsx
Labels: 리팩토링 🔨

#129 feat: 컬럼 카드 검색기능 및 카드 모달 최신화 추가
  components/dashboard/column.tsx
  components/modal/create-card/CreateCardModal.tsx
  components/modal/edit-column/DeleteColumnConfirmModal.tsx
  components/modal/edit-column/EditColumnModal.tsx
Labels: 기능구현 🚀

#133 feat: 인터렉티브한 랜딩페이지 만들기
  pages/index.tsx
Labels: 기능구현 🚀

#131 feat: persist 데이터 동기화 usePersistedStore 훅 추가
  hooks/usePersistStore.ts
Labels: 버그 🐞, 기능구현 🚀

#134 fix: 헤더 프로필 드롭다운 위치 수정, 멤버 목록 스크롤, 대시보드 설정 접근 제한, 초대하기 성공 안내 추가
  components/common/DropdownMenu.tsx
  components/dashboard/header/DashboardHeader.tsx
  components/dashboard/header/Header.tsx
  components/dashboard/header/HeaderMembers.tsx
  components/dashboard/header/ProfileDropdownMenu.tsx
  components/modal/Invite/InviteModal.tsx
  hooks/useOnClickOutside.ts
Labels: 버그 🐞, 리팩토링 🔨

#139 refactor: 드롭다운 수정
  components/modal/DropdownManager.tsx
  components/modal/DropdownState.tsx
  components/modal/SelectDate.tsx
  components/modal/create-card/CreateCardModal.tsx
  components/modal/edit-card/EditCardModal.tsx
  styles/globals.css
Labels: 리팩토링 🔨

#132 fix: AccessToken unauthorized 오류 해결
  components/boardEdit/BoardEditMain.tsx
  components/boardEdit/DeleteDashboardConfirmModal.tsx
  components/boardEdit/InviteListTable.tsx
  components/boardEdit/MembersTable.tsx
  components/boardEdit/NameEditForm.tsx
  components/boardEdit/data/useDeleteDashboard.ts
  components/boardEdit/data/useDeleteMember.ts
  components/boardEdit/data/useGetDashboard.ts
  components/boardEdit/data/useGetDashboardInvitaions.ts
  components/boardEdit/data/useGetMembers.ts
  components/boardEdit/data/usePutDashboard.ts
  components/dashboard/column.tsx
  components/dashboard/data/useGetCards.ts
  components/dashboard/data/useGetColums.ts
  components/dashboard/data/useGetDashboards.tsx
  components/dashboard/header/HeaderMembers.tsx
  components/dashboard/header/ProfileDropdownMenu.tsx
  components/index.ts
  components/modal/Invite/InviteModal.tsx
  components/modal/create-card/CreateCardModal.tsx
  components/modal/create-column/createColumnModal.tsx
  components/modal/data/useDeleteColumns.tsx
  components/modal/data/usePostCard.tsx
  components/modal/data/usePutColumns.ts
  components/modal/edit-column/DeleteColumnConfirmModal.tsx
  components/modal/edit-column/EditColumnModal.tsx
  components/myBoard/data/useGetDashBoards.ts
  components/myBoard/data/usePutInvitations.ts
  components/mydashboard/DashBoards.tsx
  components/mydashboard/InvitationsDashBoards.tsx
  components/mydashboard/MyDashBoards.tsx
  components/mydashboard/data/useGetInvitations.ts
  components/mydashboard/data/usePutInvitations.ts
  components/sign/data/index.ts
  components/sign/data/useCheckEmailDuplicate.ts
  components/sign/data/useLogin.tsx
  components/sign/form/LoginForm.tsx
  components/sign/form/SignUpForm.tsx
  hooks/useGetToken.ts
  hooks/useTokenRedirect.tsx
  pages/mydashboard/index.tsx
  store/memos/.gitkeep
  store/memos/index.ts
  store/memos/useDashboardList.ts
  store/memos/useStoreAccessToken.ts
  store/memos/useUserInfo.ts
  utils/axiosInstance.ts
Labels: 버그 🐞, 리팩토링 🔨

#142 feat: 할 일 카드 모달 추가
  components/common/DropdownMenu.tsx
  components/dashboard/column.tsx
  components/index.ts
  components/modal/todo/AsigneeCard.tsx
  components/modal/todo/CommentInput.tsx
  components/modal/todo/CommentList.tsx
  components/modal/todo/TodoModal.tsx
  components/modal/todo/data/TodoDropDownMenu.tsx
  components/modal/todo/data/useGetComments.ts
  components/modal/todo/data/usePostComments.ts
  public/icons/closeIcon.svg
  public/icons/kebabIcon.svg
  public/icons/verticalLineIcon.svg
Labels: 기능구현 🚀

#141 refactor: 할일생성 카드 제목/설명만 필수값으로 변경
  components/modal/create-card/CreateCardModal.tsx
Labels: 리팩토링 🔨

#147 refactor/카드 프로필 이미지 수정 및 할일 카드 모달 전반적 수정
  components/dashboard/column.tsx
  components/modal/todo/AsigneeCard.tsx
  components/modal/todo/CommentInput.tsx
  components/modal/todo/CommentList.tsx
  components/modal/todo/TodoModal.tsx
Labels: 리팩토링 🔨

#149 fix/카드 button 수정 및 모달 전체 크기 수
  components/dashboard/column.tsx
  components/modal/todo/TodoModal.tsx
Labels: 리팩토링 🔨

#150 refactor: 댓글 입력 후 댓글 입력 input value 비우기
  components/modal/todo/CommentInput.tsx
Labels: 리팩토링 🔨

#148 fix: 대시보드 생성모달 컬러칩 컴포넌트와 수정 페이지 컬러칩 컴포넌트 동기화 현상 수정
  components/boardEdit/EditColorChips.tsx
  components/boardEdit/NameEditForm.tsx
  components/index.ts
  pages/dashboard/[id]/edit/index.tsx
Labels: 버그 🐞, 리팩토링 🔨

#130 refactor: 마이페이지 리팩토링
  components/boardEdit/BoardEditMain.tsx
  components/index.ts
  components/mypage/MypageMain.tsx
  components/mypage/MypageProfile.tsx
  components/mypage/data/useGetUser.ts
  components/sign/constants.ts
  page-layout/MyPageLayout.tsx
  pages/mypage/index.tsx
  store/memos/useUserInfo.ts
Labels: 리팩토링 🔨

#152 fix/카드 마감일 수정
  components/dashboard/column.tsx
Labels: 리팩토링 🔨

#151 fix: axios 헤더 accessToken 추가하여 해결
  components/sign/form/LoginForm.tsx
  utils/axiosInstance.ts
Labels: 버그 🐞

#154 fix: 로그인상태에서 재접속시 axios 문제 해결
  components/boardEdit/InviteListTable.tsx
  components/boardEdit/data/useDeleteDashboard.ts
  components/boardEdit/data/useDeleteMember.ts
  components/boardEdit/data/useGetDashboard.ts
  components/boardEdit/data/useGetInvitaions.ts
  components/boardEdit/data/useGetMembers.ts
  components/boardEdit/data/usePutDashboard.ts
  components/dashboard/data/useDeleteColumns.tsx
  components/dashboard/data/useGetCards.ts
  components/dashboard/data/useGetColums.ts
  components/dashboard/data/useGetDashboards.tsx
  components/dashboard/data/usePutColumns.ts
  components/modal/ImagePick.tsx
  components/modal/create-card/data/usePostCard.tsx
  components/modal/data/usePostColumns.ts
  components/modal/data/usePostDashboards.ts
  components/modal/data/usePostInvitations.ts
  components/modal/edit-card/data/usePutCard.tsx
  components/modal/todo/CommentList.tsx
  components/modal/todo/TodoModal.tsx
  components/modal/todo/data/useGetComments.ts
  components/modal/todo/data/usePostComments.ts
  components/myBoard/data/useGetDashBoards.ts
  components/myBoard/data/useGetInvitations.ts
  components/myBoard/data/usePutInvitations.ts
  components/mypage/MypageProfile.tsx
  components/mypage/PasswordModify.tsx
  components/mypage/data/useGetUser.ts
  components/mypage/data/usePostProfileImage.ts
  components/sign/form/LoginForm.tsx
  utils/axiosInstance.ts
Labels: 버그 🐞

#153 fix: 타입 수정 및 드롭 다운 z-index 수정
  components/common/DropdownMenu.tsx
  components/dashboard/column.tsx
  components/myBoard/InvitationsDashBoards.tsx
  pages/test/index.tsx
Labels: 리팩토링 🔨

#159 feat: 할일수정 모달 연결 및 기본값 세팅 조정
  components/dashboard/column.tsx
  components/modal/DropdownManager.tsx
  components/modal/DropdownState.tsx
  components/modal/ImagePick.tsx
  components/modal/edit-card/AddTag.tsx
  components/modal/edit-card/EditCardModal.tsx
  components/modal/edit-card/data/usePutCard.tsx
  components/modal/todo/TodoModal.tsx
  components/modal/todo/data/TodoDropDownMenu.tsx
Labels: 기능구현 🚀

#160 refactor: 현재비밀번호 다름 모달 사이즈 수정, 대시보드 주인일 때 멤버 삭제 버튼 제거, 왕관 아이콘 추가
  components/boardEdit/MembersTable.tsx
  components/mypage/MypageProfile.tsx
  components/mypage/PasswordModify.tsx
Labels: 리팩토링 🔨

#158 feat: 프로필 이미지, 태그 랜덤 색상 구현
  components/boardEdit/MembersTable.tsx
  components/common/DropdownMenu.tsx
  components/common/Profile.tsx
  components/common/ProfileImage.tsx
  components/common/Tag.tsx
  components/dashboard/column.tsx
  components/dashboard/header/Header.tsx
  components/dashboard/header/HeaderMembers.tsx
  components/dashboard/header/MemberInfoItem.tsx
  components/modal/DropdownManager.tsx
  components/modal/todo/AsigneeCard.tsx
  components/modal/todo/CommentList.tsx
  components/mypage/data/useGetUser.ts
  constants/constants.ts
  store/memos/useUserInfo.ts
  tailwind.config.ts
  utils/axiosInstance.ts
  utils/getRandomNum.ts
Labels: 기능구현 🚀, 리팩토링 🔨

#162 refactor: 왕관 대시보드 주인에게만 보이게 수정
  components/boardEdit/MembersTable.tsx
Labels: 리팩토링 🔨
